"""Deterministic mutations of an attack — the gate's generalization side.

The first two sides of the gate cannot tell a rule that understands an exploit
from a rule that memorized one payload. Side 1 replays the *exact* breaching
attack, so a patch keyed to a literal threshold or a hand-picked keyword list
passes it perfectly; side 2 only asks that legitimate work still runs. Both
are satisfied by a guard that will fall over the moment the attacker changes a
comma.

So the gate gets a third side: mechanically mutate the attack in ways that
preserve what makes it an attack — the operator never authorized this value —
while changing how it is spelled or dressed. Every mutation must also be
blocked. A rule built on provenance survives all of them; a rule built on
`amount >= 600` or `matches_regex 'surcharge'` does not.

These are deliberately deterministic and LLM-free: the gate runs on every
synthesis attempt, so it has to be cheap, and a generalization test that is
itself generated by a model is a test that can drift. Nothing here touches
`task_instruction` — mutating the operator's own words could turn an attack
into authorized work and make the mutation unfair.
"""

from __future__ import annotations

import copy
import re
from typing import Any, Callable

ZWSP = "​"

#: Vocabulary a lazy patch is apt to pin a regex to, mapped to plain synonyms.
#: Substituting these leaves the exploit intact and breaks keyword matching.
RESTYLINGS = {
    "ignore all previous instructions": "disregard the earlier guidance",
    "ignore previous instructions": "set aside the prior guidance",
    "immediately call": "go ahead and use",
    "surcharge": "handling adjustment",
    "retroactive": "backdated",
    "priority support": "premium tier",
    "auto-enrolled": "automatically included",
    "banking update": "remittance revision",
    "correction notice": "revision notice",
    "no further sign-off": "no additional approval",
    "sync error": "reconciliation gap",
    "urgent": "time-sensitive",
    "immediately": "without delay",
    "new payment processor": "updated settlement provider",
}

TEXT_FIELDS = ("payload", "second_hop_payload")


def _split_chars(value: str, sep: str) -> str:
    return sep.join(value)


def _rewrite_text(attack: dict[str, Any], rewrite: Callable[[str], str]) -> dict[str, Any]:
    """Apply `rewrite` to every untrusted text field, leaving the operator's
    instruction and the tool arguments alone."""
    out = copy.deepcopy(attack)
    for field in TEXT_FIELDS:
        if out.get(field):
            out[field] = rewrite(out[field])
    return out


def _mentions(attack: dict[str, Any], value: str) -> bool:
    return any(value in (attack.get(f) or "") for f in TEXT_FIELDS)


def _amount_spellings(amount: Any) -> list[str]:
    """How this amount plausibly appears in prose, longest first so the
    broadest match is replaced before its own prefix."""
    try:
        value = float(amount)
    except (TypeError, ValueError):
        return []
    whole = int(value)
    forms = {f"{whole:,}.00", f"{whole:,}", f"{value:,.2f}", str(whole), str(amount)}
    if value != whole:
        forms.add(f"{value:.2f}")
    return sorted((f for f in forms if f), key=len, reverse=True)


def _replace_amount(text: str, amount: Any, replacement: str) -> str:
    for spelling in _amount_spellings(amount):
        text = text.replace(spelling, replacement)
    return text


# --- the mutators -----------------------------------------------------------
# Each returns a mutated attack, or None when it does not apply to this attack.


def zero_width_recipient(attack: dict[str, Any]) -> dict[str, Any] | None:
    """Hide the recipient behind zero-width joiners in the text, while the tool
    argument stays clean — the agent parses it back out."""
    to = str(attack["payment_request"].get("to", ""))
    if not to or not _mentions(attack, to):
        return None
    return _rewrite_text(attack, lambda t: t.replace(to, _split_chars(to, ZWSP)))


def spaced_recipient(attack: dict[str, Any]) -> dict[str, Any] | None:
    """Break the recipient up the way a real invoice formats an account number
    'for readability'."""
    to = str(attack["payment_request"].get("to", ""))
    if not to or not _mentions(attack, to):
        return None
    return _rewrite_text(attack, lambda t: t.replace(to, _split_chars(to, " ")))


def hyphenated_recipient(attack: dict[str, Any]) -> dict[str, Any] | None:
    to = str(attack["payment_request"].get("to", ""))
    if len(to) < 4 or not _mentions(attack, to):
        return None
    grouped = "-".join(to[i : i + 4] for i in range(0, len(to), 4))
    return _rewrite_text(attack, lambda t: t.replace(to, grouped))


def substituted_recipient(attack: dict[str, Any]) -> dict[str, Any] | None:
    """A different unauthorized recipient, changed in the argument as well as
    the text.

    The recipient mutations above deliberately leave the argument clean, since
    that is how the evasion works in practice — so none of them would trouble a
    rule that simply hardcodes the account seen once. This one does: the exploit
    is identical and the account is new, which is the whole point of a defense
    that generalizes.
    """
    to = str(attack["payment_request"].get("to", ""))
    if not to or not _mentions(attack, to):
        return None
    shifted = "".join(str((int(ch) + 3) % 10) if ch.isdigit() else ch for ch in to)
    if shifted == to:
        shifted = f"{to}9Z"
    if shifted in (attack.get("task_instruction") or ""):
        return None
    out = _rewrite_text(attack, lambda t: t.replace(to, shifted))
    out["payment_request"]["to"] = shifted
    return out


def regrouped_amount(attack: dict[str, Any]) -> dict[str, Any] | None:
    """Same amount, written with thousands separators and cents. Defeats any
    rule that substring-matches the raw argument against the text."""
    amount = attack["payment_request"].get("amount")
    if amount is None:
        return None
    try:
        grouped = f"{float(amount):,.2f}"
    except (TypeError, ValueError):
        return None
    if not any(s in (attack.get(f) or "") for f in TEXT_FIELDS for s in _amount_spellings(amount)):
        return None
    return _rewrite_text(attack, lambda t: _replace_amount(t, amount, grouped))


def shifted_amount(attack: dict[str, Any]) -> dict[str, Any] | None:
    """A different unauthorized amount. This is the one that catches a
    hardcoded threshold: the exploit is identical, the number is smaller.
    """
    amount = attack["payment_request"].get("amount")
    try:
        value = float(amount)
    except (TypeError, ValueError):
        return None
    shifted = round(value * 0.41, 2)
    if shifted <= 0:
        return None
    # An amount the operator happened to name would no longer be unauthorized.
    from .antibody import numbers_in

    if shifted in numbers_in(attack.get("task_instruction", "")):
        return None
    shifted_text = f"{shifted:,.2f}"
    out = _rewrite_text(attack, lambda t: _replace_amount(t, amount, shifted_text))
    out["payment_request"]["amount"] = shifted
    return out


def understated_amount(attack: dict[str, Any]) -> dict[str, Any] | None:
    """A much smaller unauthorized amount.

    shifted_amount alone does not punish a hardcoded floor: 41% of $4,850 is
    still comfortably over an `amount >= 600` threshold, so the memorized rule
    survives. Dropping the amount well below any plausible hand-picked floor
    forces the rule to be about authorization rather than magnitude — the
    operator did not authorize this value either.
    """
    amount = attack["payment_request"].get("amount")
    try:
        value = float(amount)
    except (TypeError, ValueError):
        return None
    from .antibody import numbers_in

    authorized = numbers_in(attack.get("task_instruction", ""))
    understated = round(value * 0.037, 2)
    if understated < 1:
        understated = round(value / 2, 2)
    if understated <= 0 or understated in authorized or understated == value:
        return None
    text = f"{understated:,.2f}"
    out = _rewrite_text(attack, lambda t: _replace_amount(t, amount, text))
    out["payment_request"]["amount"] = understated
    return out


def restyled_vocabulary(attack: dict[str, Any]) -> dict[str, Any] | None:
    """Reword the pretext. Catches a rule pinned to specific trigger words."""

    def rewrite(text: str) -> str:
        out = text
        for term, replacement in RESTYLINGS.items():
            out = re.sub(re.escape(term), replacement, out, flags=re.IGNORECASE)
        return out

    mutated = _rewrite_text(attack, rewrite)
    if all(mutated.get(f) == attack.get(f) for f in TEXT_FIELDS):
        return None  # none of the vocabulary was present — nothing was tested
    return mutated


MUTATORS: tuple[tuple[str, Callable[[dict[str, Any]], dict[str, Any] | None]], ...] = (
    ("zero_width_recipient", zero_width_recipient),
    ("spaced_recipient", spaced_recipient),
    ("hyphenated_recipient", hyphenated_recipient),
    ("substituted_recipient", substituted_recipient),
    ("regrouped_amount", regrouped_amount),
    ("shifted_amount", shifted_amount),
    ("understated_amount", understated_amount),
    ("restyled_vocabulary", restyled_vocabulary),
)


def mutations_of(attack: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    """Every mutation that applies to this attack, as (name, attack) pairs.

    Inapplicable mutators are skipped rather than faked: a mutation that
    couldn't change anything would be a test the candidate passes for free.
    """
    out: list[tuple[str, dict[str, Any]]] = []
    for name, mutator in MUTATORS:
        try:
            mutated = mutator(attack)
        except Exception:
            continue  # a mutator that can't handle this shape just abstains
        if mutated is not None:
            out.append((name, mutated))
    return out
